// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhnY2SYS-vhWdi9gf3dOJdL6KCTeLxk5Y',
    appId: '1:693999666355:web:49d7d43a03195e09541cc6',
    messagingSenderId: '693999666355',
    projectId: 'dev-nexus-7208a',
    authDomain: 'dev-nexus-7208a.firebaseapp.com',
    storageBucket: 'dev-nexus-7208a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRLC1IxT3zRg_0BlcwGah5efftXs8b94E',
    appId: '1:693999666355:android:76093288acc4edae541cc6',
    messagingSenderId: '693999666355',
    projectId: 'dev-nexus-7208a',
    storageBucket: 'dev-nexus-7208a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1Ai9D65iFAZ3m9EypV3U0mUeahYsa1w',
    appId: '1:693999666355:ios:c6ad055c7529ceea541cc6',
    messagingSenderId: '693999666355',
    projectId: 'dev-nexus-7208a',
    storageBucket: 'dev-nexus-7208a.firebasestorage.app',
    iosBundleId: 'com.devnexus.devNexus',
  );

}